# hello-world-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  labels:
    app: hello-world
spec:
  replicas: 2 # Run two instances of the pod
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world-container
        image: nginx:latest # Using nginx as a simple web server for "hello world"
        ports:
        - containerPort: 80 # Nginx listens on port 80

---
# hello-world-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 8080 # Service port
      targetPort: 80 # Container port
  type: LoadBalancer # Expose the service externally
