apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin-container
        image: dpage/pgadmin4:latest
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@admin.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: root
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  annotations:
    service.kubernetes.io/kind-ingress: "true" #important for kind
spec:
  type: LoadBalancer
  selector:
    app: pgadmin
  ports:
  - protocol: TCP
    port: 443
    targetPort: 80
